import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration to drop the auto-generated unique constraint on staff_profiles.userId
 * that was created by the @OneToOne(() => User) decorator.
 *
 * The relationship is being changed to @ManyToOne(() => User) to allow a single
 * user to have multiple staff profiles across different merchants. The composite
 * unique constraint on ("merchantId", "userId") already enforces the correct
 * business rule: one profile per (merchant, user) pair.
 *
 * TypeORM 0.3 names relation constraints as REL_<sha1>, so we use dynamic SQL
 * to find and drop any single-column unique/relation constraints on userId.
 */
export class DropStaffProfileUserIdRelationConstraint1750000000000
  implements MigrationInterface
{
  name = 'DropStaffProfileUserIdRelationConstraint1750000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Drop any single-column unique constraints on "userId" in staff_profiles
    // that were auto-generated by @OneToOne (named REL_<hash> by TypeORM 0.3).
    // We keep the composite unique constraint UQ_staff_profiles_merchantId_userId.
    await queryRunner.query(`
      DO $$
      DECLARE
        con_row RECORD;
      BEGIN
        FOR con_row IN
          SELECT con.conname
          FROM pg_catalog.pg_constraint con
          JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
          WHERE rel.relname = 'staff_profiles'
            AND con.contype = 'u'
            AND con.conkey::text IN (
              SELECT ('{' || a.attnum || '}')::text
              FROM pg_catalog.pg_attribute a
              WHERE a.attrelid = rel.oid
                AND a.attname = 'userId'
            )
            AND array_length(con.conkey, 1) = 1
        LOOP
          EXECUTE 'ALTER TABLE "staff_profiles" DROP CONSTRAINT "' || con_row.conname || '"';
        END LOOP;
      END $$;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Re-create the unique constraint on userId that @OneToOne auto-generated.
    // Note: this is a best-effort restore. The original constraint was
    // auto-named by TypeORM (REL_<hash>), so we restore it without a
    // specific name and let TypeORM re-create it if synchronize is enabled.
    //
    // If the app is running with synchronize:false, you may need to run
    // `pnpm run migration:generate` to let TypeORM detect the diff.
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM pg_catalog.pg_constraint con
          JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
          WHERE rel.relname = 'staff_profiles'
            AND con.contype = 'u'
            AND con.conkey::text IN (
              SELECT ('{' || a.attnum || '}')::text
              FROM pg_catalog.pg_attribute a
              WHERE a.attrelid = rel.oid
                AND a.attname = 'userId'
            )
            AND array_length(con.conkey, 1) = 1
        ) THEN
          ALTER TABLE "staff_profiles"
            ADD CONSTRAINT "UQ_staff_profiles_userId"
            UNIQUE ("userId");
        END IF;
      END $$;
    `);
  }
}
